# Generated by Django 2.2.5 on 2020-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
